name:                android-localization-tool
version:             0.1.0.0
github:              "githubuser/android-localization-tool"
license:             BSD3
author:              "Henry Hsuan-Ju Chen"
maintainer:          "hsuanju.ch@gmail.com"
copyright:           "2018 Henry Hsuan-Ju Chen"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/android-localization-tool#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - hxt
    - hxt-curl
    - containers
    - directory
    - xlsx
    - text
    - bytestring

executables:
  to_csv:
    main:                to_csv.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - android-localization-tool

  merge_xlsx:
    main: mergeXlsx.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - android-localization-tool
    - hxt


  exp:
    main: exp.hs
    source-dirs: exp
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - android-localization-tool
    - hxt
    - hxt-curl
    - containers
    - directory
    - xlsx
    - bytestring
    - text
    - lens

  exp2:
    main: exp2.hs
    source-dirs: exp
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - android-localization-tool
    - hxt
    - hxt-curl
    - containers
    - directory

  to_xlsx:
    main: to_xlsx.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - android-localization-tool
    - xlsx
    - lens
    - bytestring
    - text
    - time
    - containers
    - directory

tests:
  android-localization-tool-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - android-localization-tool
